title: HiConfiT
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/hiconfit.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/hiconfit.png"
description: High Performance Knowledge Based Configuration Techniques
theme: just-the-docs

# url: https://just-the-docs.github.io
url: https://hiconfit.manleviet.info

aux_links:
    HiConfiT on GitHub: https://github.com/HiConfiT
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

mermaid:
    # Version of mermaid library
    # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
    version: "9.1.3"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022-2023 <a href=\"https://beta.manleviet.info\">Viet-Man Le</a>. Distributed by an <a href=\"https://github.com/HiConfiT/hiconfit.github.io/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts_level: quiet # or loud
callouts:
    highlight:
        color: yellow
    important:
        title: Important
        color: blue
    new:
        title: New
        color: green
    note:
        title: Note
        color: purple
    warning:
        title: Warning
        color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
ga_tracking: G-DKNNGSKV4Q
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# For copy button on code
enable_copy_code_button: true

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex